plot.xvg<-function(file){
  data<-read.xvg(file)
  X<-readLines(file)
  P1<-grep(pattern="title",x=X[1:length(X)])
  plot(data[,1],data[,2],type="l",
       main=(scan(file,skip=min(P1)-1,nmax=min(P1)+2,what="",quiet=TRUE)[3]),
       xlab=(scan(file,skip=min(P1)-1,nmax=min(P1)+2,what="",quiet=TRUE)[7]),
       ylab=(scan(file,skip=min(P1)-1,nmax=min(P1)+2,what="",quiet=TRUE)[11]))
}