# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chargeList <- function(seq, pH, pKscale = "Lehninger") {
    .Call('Peptides_chargeList', PACKAGE = 'Peptides', seq, pH, pKscale)
}

absoluteCharge <- function(seq, pH = 7, pKscale = "Lehninger") {
    .Call('Peptides_absoluteCharge', PACKAGE = 'Peptides', seq, pH, pKscale)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('Peptides_RcppExport_registerCCallable', PACKAGE = 'Peptides')
})
