# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateCharge <- function(seq, pH = 7, pKscale = "Lehninger") {
    .Call('Peptides_calculateCharge', PACKAGE = 'Peptides', seq, pH, pKscale)
}

pHsequence <- function(seq, pH, pKscale = "Lehninger") {
    .Call('Peptides_pHsequence', PACKAGE = 'Peptides', seq, pH, pKscale)
}

sequenceList <- function(seq, pH, pKscale = "Lehninger") {
    .Call('Peptides_sequenceList', PACKAGE = 'Peptides', seq, pH, pKscale)
}

